[colors]
; Цветовая схема как на картинке (Toji/Night)
bg = #0f0f12
fg = #a9b1d6
cyan = #7dcfff
module_bg_1 = #16161e
module_bg_2 = #1f1f28

[bar/main]
width = 100%
height = 28
radius = 0
fixed-center = true
bottom = false

; Очень тонкая граница сверху бара
border-size = 0
background = ${colors.bg}
foreground = ${colors.fg}

padding-left = 1
padding-right = 1

module-margin-left = 0
module-margin-right = 0

font-0 = "JetBrainsMono Nerd Font:style=Bold:size=9;2"
font-1 = "Symbols Nerd Font:size=11;3"

modules-left = bspwm
modules-center = center-icons date
modules-right = memory battery powermenu

; ----------------- МОДУЛИ L -----------------

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
format = <label-state> <label-mode>
index-sort = true
enable-scroll = false

format-background = ${colors.module_bg_1}

; Настройки внешнего вида цифр (рабочих столов)
label-focused = " %name% "
label-focused-foreground = ${colors.cyan}
label-focused-background = ${colors.module_bg_2}

label-occupied = " %name% "
label-occupied-foreground = ${colors.fg}

label-empty = " %name% "
label-empty-foreground = #444444

label-separator = " "

; ----------------- МОДУЛИ C -----------------

[module/center-icons]
type = custom/text
; Эти символы перед временем как на картинке
content = ">_ -/- [] <>"
content-foreground = ${colors.cyan}
content-margin = 1

[module/date]
type = internal/date
interval = 5
; Формат времени как на картинке
time = "%H:%M"
label = " %time% "
label-foreground = ${colors.fg}

; ----------------- МОДУЛИ R -----------------

[module/memory]
type = internal/memory
interval = 3
format = <label>
format-prefix = "  "
format-prefix-foreground = ${colors.cyan}
format-background = ${colors.module_bg_1}
; На картинке RAM в GIB
label = " %gb_used% "

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98

format-charging = <label-charging>
format-charging-prefix = "  "
format-charging-background = ${colors.module_bg_2}
format-charging-prefix-foreground = ${colors.cyan}

format-discharging = <label-discharging>
format-discharging-prefix = "  "
format-discharging-background = ${colors.module_bg_2}
format-discharging-prefix-foreground = ${colors.fg}

label-charging = " %percentage%% "
label-discharging = " %percentage%% "

[module/powermenu]
type = custom/text
content = "  "
content-foreground = ${colors.fg}
content-background = ${colors.module_bg_1}
content-padding = 1
click-left = poweroff
